// <auto-generated />
using AirGradientAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirGradientAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231115230809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirGradientAPI.Entities.SensorDatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Atmp")
                        .HasColumnType("real");

                    b.Property<string>("ChipId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pm02")
                        .HasColumnType("integer");

                    b.Property<int>("Rco2")
                        .HasColumnType("integer");

                    b.Property<int>("Rhum")
                        .HasColumnType("integer");

                    b.Property<int>("Wifi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SensorData");
                });
#pragma warning restore 612, 618
        }
    }
}
